# -*- coding: utf-8 -*-
"""RTES_World_Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjOImv4_tscFWDUenxYbREyYuHNaOd49
"""



import pandas as pd
import plotly.express as px

# covid_csv_dataset = 'https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv'
covid_csv_dataset = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"

total_cases_data = pd.read_csv(covid_csv_dataset)

total_cases_data.tail()

world_map = px.choropleth(
    total_cases_data,
    locations = 'location',
    locationmode = 'country names',
    color = 'total_cases_per_million',
    animation_frame = 'date')
world_map.update_layout(title_text = 'COVID-19 Trends from the beginning of time')
world_map.show()

